_format_version: "2.1"
_transform: true

services:
  - name: example-service
    url: https://mockbin.org
    plugins:
      - name: clacks
        config:
          jwt_expiration: "12h"
      - name: file-log
        config: 
          path: /tmp/file.log
    routes:
      - name: jspath
        paths:
        - /
        
